/**
 * query.ts — Shared TypeScript types for the AI SQL Analyst.
 *
 * These types describe the shape of data flowing through the app:
 *   User input → API request → API response → UI display
 *
 * Day 4: The real POST /api/v1/mcp/query response will match QueryResult exactly.
 * Day 3: We use MockQueryResult to simulate this shape.
 */

// ── Query lifecycle ───────────────────────────────────────────────────────────

/** Status of the current query request */
export type QueryStatus = 'idle' | 'loading' | 'success' | 'error'

/** Chart view the user has selected */
export type ChartType = 'bar' | 'line' | 'pie'

// ── API response shape ────────────────────────────────────────────────────────

/**
 * The result returned after processing a natural-language question.
 * Day 4: POST /api/v1/mcp/query will return this exact structure.
 */
export interface QueryResult {
  /** The SQL query generated by the LLM (read-only, validated) */
  sql: string
  /** Column names from the database result */
  columns: string[]
  /** Result rows — each row is a record of column → value */
  rows: Record<string, unknown>[]
  /** How long the SQL execution took in milliseconds */
  executionTimeMs: number
  /** Total number of rows returned */
  rowCount: number
}

// ── Service status ────────────────────────────────────────────────────────────

/** Connection status of a dependent service */
export type ServiceConnectionStatus = 'connected' | 'disconnected' | 'checking'

/** Represents one service shown in the status bar */
export interface ServiceStatus {
  /** Display name, e.g. "Backend", "Database", "LLM" */
  name: string
  status: ServiceConnectionStatus
  /** Optional note shown below the badge */
  note?: string
}
